name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Local install
      run: |
        python -m pip install --upgrade pip wheel
        cd subdir
        python -m pip install --upgrade .

    - name: List installed Python packages
      run: python -m pip list

    - name: Build a sdist and wheel
      run: |
        cd subdir
        pipx run build .

    - name: Verify the distribution
      run: |
        cd subdir
        pipx run twine check --strict dist/*

    - name: List contents of sdist
      run: |
        cd subdir
        python -m tarfile --list dist/pyhf-*.tar.gz

    - name: List contents of wheel
      run: |
        cd subdir
        python -m zipfile --list dist/pyhf-*.whl
