name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Local install
      run: |
        python -m pip install --upgrade pip wheel
        cd subdir
        python -m pip install .

    - name: List installed Python packages
      run: python -m pip list

    - name: Cleanup to have dist build be as clean as possible
      run: |
        cd subdir
        rm -rf src/example_pkg/_version.py
        rm -rf build

      # c.f. https://github.com/scikit-build/scikit-build-core/issues/495
    - name: Build a sdist and wheel
      run: |
        cd subdir
        # pipx run build .
        python -m pip install --upgrade build
        python -m build .

    - name: Verify the distribution
      run: |
        cd subdir
        pipx run twine check --strict dist/*

    - name: List contents of sdist
      run: |
        cd subdir
        python -m tarfile --list dist/example_pkg-*.tar.gz

    - name: List contents of wheel
      run: |
        cd subdir
        python -m zipfile --list dist/example_pkg-*.whl
